### PR TITLE
fix changelog version selection

### PR DESCRIPTION
**Pull request by ghost**
When a device is transitioned to a newer branch (eg 14.1 to 15.1), the changelogs continue to show the old branch, because the first (oldest) nightly in a device's nightly list is used to decide the branch version (line 135). Choose the newest instead.

### CODE REVIEW

**Comment by fourkbomb** [comment]
Thanks for the PR. We do need you do sign the CLA before we can merge this, though. Thanks :)

**Comment by ghost** [comment]
Sorry, have just been waiting for a chance to set everything up on docker for testing.
I've just tried it all and ended up changing it to select the last (most recent) nightly rather than reversing the list.

**Comment by akca** [comment]
This works. I tested this without knowing this PR, sent a new one: https://github.com/lineageos-infra/updater/pull/11
Later, I realized that the exact same commit was sent by another one before me!

**Comment by zifnab06** [comment]
This was done in #11, going to close this, thanks though!

**Pull request closed without merging**
